Urls = [
    "https://daffodilvarsity.edu.bd/tuition-fee-calculator",
    "http://daffodilvarsity.edu.bd/article/life-insurance",
    "https://daffodilvarsity.edu.bd/departments",
    "https://daffodilvarsity.edu.bd/article/deans-heads",
    "https://daffodilvarsity.edu.bd/article/associate-deans-heads",
    "https://daffodilvarsity.edu.bd/article/international-adviser",
    "https://daffodilvarsity.edu.bd/article/visiting-professors",
    "https://daffodilvarsity.edu.bd/lecture-series",
    "https://daffodilvarsity.edu.bd/bscic",
    "https://daffodilvarsity.edu.bd/daycare",
    "https://daffodilvarsity.edu.bd/noticeboard",
    "https://daffodilvarsity.edu.bd/article/student-activities",
    "https://daffodilvarsity.edu.bd/virtual-tour",
    "https://daffodilvarsity.edu.bd/article/industrial-linkage",
    "https://daffodilvarsity.edu.bd/delegates/delegates-abroad",
    "https://daffodilvarsity.edu.bd/csr-activities",
]
